### ISSUE TITLE
Installation issue on Fenixedu-academic

### ISSUE THREAD

**Issue by vairamuthuraj** [FenixEdu/fenixedu.github.io#30]
Hi Team,

We are trying to install your application(fenixedu academic) by following the instruction given in the below link 
http://fenixedu.org/dev/tutorials/install-fenix-edu/

We have mentioned the sample error message below, while starting the tomcat using the  command 
cd fenix-webapp
mvn tomcat7:run

Error: Couldn't load class net.sourceforge.fenixedu.domain.transactions.InsuranceTransaction: java.lang.ClassNotFoundException: net.sourceforge.fenixedu.domain.transactions.InsuranceTransaction
Error: Couldn't load class net.sourceforge.fenixedu.domain.period.DegreeCandidacyForGraduatedPersonCandidacyPeriod: java.lang.ClassNotFoundException: net.sourceforge.fenixedu.domain.period.DegreeCandidacyForGraduatedPersonCandidacyPeriod
Error: Couldn't load class net.sourceforge.fenixedu.domain.homepage.Homepage: java.lang.ClassNotFoundException: net.sourceforge.fenixedu.domain.homepage.Homepage
Error: Couldn't load class net.sourceforge.fenixedu.domain.internship.InternshipCandidacy: java.lang.ClassNotFoundException: net.sourceforge.fenixedu.domain.internship.InternshipCandidacy
Error: Couldn't load class net.sourceforge.fenixedu.domain.teacher.PublicationsNumber: java.lang.ClassNotFoundException: net.sourceforge.fenixedu.domain.teacher.PublicationsNumber
Error: Couldn't load class net.sourceforge.fenixedu.domain.student.curriculum.ExtraCurricularActivity: java.lang.ClassNotFoundException: net.sourceforge.fenixedu.domain.student.curriculum.ExtraCurricularActivity
Error: Couldn't load class net.sourceforge.fenixedu.domain.personnelSection.contracts.PersonProfessionalRelation: java.lang.ClassNotFoundException: net.sourceforge.fenixedu.domain.personnelSection.contracts.PersonProfessionalRelation
Error: Couldn't load class net.sourceforge.fenixedu.domain.accounting.events.serviceRequests.PastCertificateRequestEvent: java.lang.ClassNotFoundException: net.sourceforge.fenixedu.domain.accounting.events.serviceRequests.PastCertificateRequestEvent
Error: Couldn't load class net.sourceforge.fenixedu.domain.studentCurriculum.NoCourseGroupCurriculumGroup: java.lang.ClassNotFoundException: net.sourceforge.fenixedu.domain.studentCurriculum.NoCourseGroupCurriculumGro

Also, we were able to see few screens but not complete. Please guide us on the next steps to be followed as we need the project at the earliest for  our analyisis.

Environment used:
OS -  Windows 7
DB - MySQL
Java - 8

Thanks,
Vairammuthuraj

**Comment by nurv** [comment]
Hi there!

Our website is being upgraded and doesn't have all the information. All our documentation is available here: 

https://confluence.fenixedu.org/display/ACADEMIC/Welcome

**Comment by vairamuthuraj** [comment]
Hi nurv,

Thanks for quick response.We have also tried the installation procedure available in your latest link.
https://confluence.fenixedu.org/display/ACADEMIC/Welcome

We are facing the same issue.Please advise me whether we are missing any step.Expecting your reply.

Thanks,
Vairamuthuraj.

**Comment by nurv** [comment]
@vairamuthuraj we have updated https://confluence.fenixedu.org/display/ACADEMIC/Installation so now you should be able to start with the latest version on FenixEdu Academic. 

Thanks!

**Comment by vairamuthuraj** [comment]
@nurv Thank you very much for your kind and timely help. 

We followed your new instructions and able to install the application successfully.
We will reach you for further queries if required.
Thanks again.

**Comment by vairamuthuraj** [comment]
@nurv could you please share the latest user guide to setup the application, as we could see some discrepancy between the application and your user guide provided in the link.
https://confluence.fenixedu.org/display/ACADEMIC/Getting+Started
Thank you!

**Comment by nurv** [comment]
Could you give me some information where the discrepancy is?

**Comment by vairamuthuraj** [comment]
@nurv, we followed the steps as in the above link and when we try to create academic office we are getting the following exception.

Create Academic office
error : javax.servlet.ServletException
javax.servlet.ServletException: jvstm.cps.ConsistencyException: Object org.fenixedu.academic.domain.administrativeOffice.AdministrativeOffice:283330402582533 is inconsistent according to the consistency predicate: org.fenixedu.academic.domain.administrativeOffice.AdministrativeOffice_Base.checkMultiplicityOfCoordinator 

Our main requirement is to use your student information module, so we tried to create a student but we ended up in an exception which is in Portuguese. We have mailed you the exception since we were not able to attach the same here. Please check the exception and advice.

**Comment by fairouzCH** [comment]
hi, 
we are trying to install fenixedu academic in local machine (ubuntu 16.04.1) but having this problem
can you help us please 

13:17:52.682 [waitingForLeaseTimer] INFO  o.f.b.s.domain.SchedulerSystem - Create sensible default /tmp/1476357472681-0 for logging storage
out 13, 2016 1:17:52 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.fenixedu.academic.servlet.FenixInitializer
java.lang.NoClassDefFoundError: org/fenixedu/bennu/core/rest/SystemResource
	at org.fenixedu.academic.servlet.FenixInitializer.registerHealthchecks(FenixInitializer.java:67)
	at org.fenixedu.academic.servlet.FenixInitializer.advised$contextInitialized(FenixInitializer.java:63)
	at org.fenixedu.academic.servlet.FenixInitializer$callable$contextInitialized.call(Advice Library Automatically Generated Class)
	at pt.ist.fenixframework.backend.jvstmojb.JvstmOJBTransactionManager.handleReadCommand(JvstmOJBTransactionManager.java:159)
	at pt.ist.fenixframework.backend.jvstmojb.JvstmOJBTransactionManager.withTransaction(JvstmOJBTransactionManager.java:144)
	at pt.ist.fenixframework.atomic.AtomicContext.perform(AtomicContext.java:30)
	at org.fenixedu.academic.servlet.FenixInitializer.contextInitialized(FenixInitializer.java)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.fenixedu.bennu.core.rest.SystemResource
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
	... 16 more

13:17:53.272 [waitingForLeaseTimer] INFO  o.f.b.s.domain.SchedulerSystem - Running Scheduler bootstrap
out 13, 2016 1:17:53 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
out 13, 2016 1:17:53 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/demo-webapp] startup failed due to previous errors
13:17:53.552 [localhost-startStop-1] INFO  o.f.b.s.domain.SchedulerSystem - stopping scheduler
13:17:53.631 [localhost-startStop-1] WARN  org.fenixedu.bennu.signals.Signal - Detaching all handlers. Be sure what you are doing.
13:17:53.631 [localhost-startStop-1] INFO  pt.ist.fenixframework.FenixFramework - Shutting down...
13:17:53.631 [localhost-startStop-1] INFO  p.i.f.b.jvstmojb.repository.ServerId - Clearing server id lease.
13:17:53.690 [localhost-startStop-1] INFO  p.i.f.b.jvstmojb.repository.DbUtil - Successfully deregistered JDBC driver com.mysql.jdbc.NonRegisteringDriver@6a6e0202
13:17:53.690 [localhost-startStop-1] INFO  pt.ist.fenixframework.FenixFramework - Shutdown complete.
13:17:53.691 [localhost-startStop-1] INFO  o.f.b.c.s.BennuCoreContextListener - Killing initiated thread: Thread[FileDeleterThread,5,main] of class java.lang.Thread
out 13, 2016 1:17:53 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/demo-webapp] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
out 13, 2016 1:17:53 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/demo-webapp] registered the JDBC driver [com.mysql.fabric.jdbc.FabricMySQLDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
out 13, 2016 1:17:53 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]

**Comment by buho** [comment]
Hi.

I'm trying to use the initilization tool located at https://start.fenixedu.org/webapp, but it doesn't work for me.
I can't exapnd the "Fenix Edu Maven Version" and "Bennu Version" combo boxes. There are no items to select from.

I was trying to use the manual aproach using the maven archetype with no success.

I will apreciate your help.

Thank you very much.

**Comment by buho** [comment]
I have the same problem reported by vairamuthuraj  and fairouzCH.
Appears whe running the mvn tomcat7:run command.

java.lang.NoClassDefFoundError: org/fenixedu/bennu/core/rest/SystemResource
        at org.fenixedu.academic.servlet.FenixInitializer.registerHealthchecks(FenixInitializer.java:67)
        at org.fenixedu.academic.servlet.FenixInitializer.advised$contextInitialized(FenixInitializer.java:63)
        at org.fenixedu.academic.servlet.FenixInitializer$callable$contextInitialized.call(Advice Library Automatically 

I will apreciate your help.

**Comment by buho** [comment]
Now it's working using Bennu version 3.4.4 and working from an Ubuntu Desktop installation.

Thanks.
